// packages/govtnz-ds/build_src/react-js-styled-components/H7.js
import React from "react";
import styled from "styled-components";

const StyledH7 = styled.h7`
  ${props =>
    props.styleSize === "xlarge" &&
    styled.css`
      color: #2a2a2a;
      font-family: Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      font-weight: g-heading-font-weight;
      font-size: 2rem;
      line-height: 1.125;
      display: block;
      margin-top: 0;
      margin-bottom: 1rem;
    `}
  @media print {
    ${props =>
      props.styleSize === "xlarge" &&
      styled.css`
        color: #000000;
      `};
  }
  @media print {
    ${props =>
      props.styleSize === "xlarge" &&
      styled.css`
        font-family: sans-serif;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props =>
      props.styleSize === "xlarge" &&
      styled.css`
        font-size: 3.5rem;
        line-height: 1.15;
      `};
  }
  @media print {
    ${props =>
      props.styleSize === "xlarge" &&
      styled.css`
        font-size: 32pt;
        line-height: 1.15;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props =>
      props.styleSize === "xlarge" &&
      styled.css`
        margin-bottom: 1rem;
      `};
  }
  ${props =>
    props.styleSize === "large" &&
    styled.css`
      color: #2a2a2a;
      font-family: Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      font-weight: g-heading-font-weight;
      font-size: 2rem;
      line-height: 1.2;
      display: block;
      margin-top: 3.5rem;
      margin-bottom: 0.5rem;
    `}
  @media print {
    ${props =>
      props.styleSize === "large" &&
      styled.css`
        color: #000000;
      `};
  }
  @media print {
    ${props =>
      props.styleSize === "large" &&
      styled.css`
        font-family: sans-serif;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props =>
      props.styleSize === "large" &&
      styled.css`
        font-size: 2.5rem;
        line-height: 1.25;
      `};
  }
  @media print {
    ${props =>
      props.styleSize === "large" &&
      styled.css`
        font-size: 24pt;
        line-height: 1.05;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props =>
      props.styleSize === "large" &&
      styled.css`
        margin-bottom: 30px;
      `};
  }
  ${props =>
    props.styleSize === "medium" &&
    styled.css`
      color: #0b0c0c;
      font-family: Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      font-weight: g-heading-font-weight;
      font-size: 1.5rem;
      line-height: 1.25;
      display: block;
      margin-top: 2.5rem;
      margin-bottom: 0.5rem;
    `}
  @media print {
    ${props =>
      props.styleSize === "medium" &&
      styled.css`
        color: #000000;
      `};
  }
  @media print {
    ${props =>
      props.styleSize === "medium" &&
      styled.css`
        font-family: sans-serif;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props =>
      props.styleSize === "medium" &&
      styled.css`
        font-size: 1.5rem;
        line-height: 1.25;
      `};
  }
  @media print {
    ${props =>
      props.styleSize === "medium" &&
      styled.css`
        font-size: 18pt;
        line-height: 1.15;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props =>
      props.styleSize === "medium" &&
      styled.css`
        margin-bottom: 0.5rem;
      `};
  }
  ${props =>
    props.styleSize === "small" &&
    styled.css`
      color: #2a2a2a;
      font-family: Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      font-weight: g-heading-font-weight;
      font-size: 1.25rem;
      line-height: 1.25;
      display: block;
      margin-top: 2.5rem;
      margin-bottom: 0.5rem;
    `}
  @media print {
    ${props =>
      props.styleSize === "small" &&
      styled.css`
        color: #000000;
      `};
  }
  @media print {
    ${props =>
      props.styleSize === "small" &&
      styled.css`
        font-family: sans-serif;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props =>
      props.styleSize === "small" &&
      styled.css`
        font-size: 1.1875rem;
        line-height: 1.31579;
      `};
  }
  @media print {
    ${props =>
      props.styleSize === "small" &&
      styled.css`
        font-size: 14pt;
        line-height: 1.15;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props =>
      props.styleSize === "small" &&
      styled.css`
        margin-bottom: 0.5rem;
      `};
  }
  padding-top: 5px;
  @media (min-width: 40.0625em) {
    padding-top: 10px;
  }
  padding-top: 15px;
  @media (min-width: 40.0625em) {
    padding-top: 20px;
  }
  padding-top: 5px;
  @media (min-width: 40.0625em) {
    padding-top: 10px;
  }
  ${props =>
    props.styleSize === "xsmall" &&
    styled.css`
      color: #2a2a2a;
      font-family: Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      font-weight: g-heading-font-weight;
      font-size: 1.125rem;
      line-height: 1.25;
      display: block;
      margin-top: 2.5rem;
      margin-bottom: 0.5rem;
    `}
  @media print {
    ${props =>
      props.styleSize === "xsmall" &&
      styled.css`
        color: #000000;
      `};
  }
  @media print {
    ${props =>
      props.styleSize === "xsmall" &&
      styled.css`
        font-family: sans-serif;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props =>
      props.styleSize === "xsmall" &&
      styled.css`
        font-size: 0.9375rem;
        line-height: 1.31579;
      `};
  }
  @media print {
    ${props =>
      props.styleSize === "xsmall" &&
      styled.css`
        font-size: 13pt;
        line-height: 1.15;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props =>
      props.styleSize === "xsmall" &&
      styled.css`
        margin-bottom: 0.5rem;
      `};
  }
  padding-top: 5px;
  @media (min-width: 40.0625em) {
    padding-top: 10px;
  }
  ${props =>
    props.styleSize === "xxsmall" &&
    styled.css`
      color: #2a2a2a;
      font-family: Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      font-weight: g-heading-font-weight;
      font-size: 1rem;
      line-height: 1.25;
      display: block;
      margin-top: 2.5rem;
      margin-bottom: 15px;
    `}
  @media print {
    ${props =>
      props.styleSize === "xxsmall" &&
      styled.css`
        color: #000000;
      `};
  }
  @media print {
    ${props =>
      props.styleSize === "xxsmall" &&
      styled.css`
        font-family: sans-serif;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props =>
      props.styleSize === "xxsmall" &&
      styled.css`
        font-size: 0.875rem;
        line-height: 1.31579;
      `};
  }
  @media print {
    ${props =>
      props.styleSize === "xxsmall" &&
      styled.css`
        font-size: 12pt;
        line-height: 1.15;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props =>
      props.styleSize === "xxsmall" &&
      styled.css`
        margin-bottom: 20px;
      `};
  }
  padding-top: 5px;
  @media (min-width: 40.0625em) {
    padding-top: 10px;
  }
  ${props =>
    props.marginBottom8 &&
    styled.css`
      margin-bottom: 8px;
    `}
  ${props =>
    props.marginBottom0 &&
    styled.css`
      margin-bottom: 0px;
    `}
margin-top: 0px;
`;

const H7 = ({ styleSize, marginBottom8, marginBottom0, id, children }) => (
  <StyledH7
    styleSize={styleSize}
    marginBottom8={marginBottom8}
    marginBottom0={marginBottom0}
    id={id}
  >
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Example text</React.Fragment>
    )}
  </StyledH7>
);

export default H7;

// packages/govtnz-ds/build_src/vue-js/H7.vue
<template>
  <h7 v-bind:class="computed__class" v-bind:id="id">
    <slot></slot>
  </h7>
</template>
<script>
import Vue from "vue";

const constants = {
  styleSize: {
    xlarge: "g-heading-xl",
    large: "g-heading-l",
    medium: "g-heading-m",
    small: "g-heading-s",
    xsmall: "g-heading-xs",
    xxsmall: "g-heading-xxs"
  }
};

export default Vue.extend({
  props: {
    styleSize: {
      type: String,
      validator: value => {
        return (
          ["xlarge", "large", "medium", "small", "xsmall", "xxsmall"].indexOf(
            value
          ) !== -1
        );
      },
      required: true
    },
    marginBottom8: { type: Boolean, default: false, required: false },
    marginBottom0: { type: Boolean, default: false, required: false },
    id: { type: String, required: false },
    children: { required: false, default: "Example text" }
  },
  computed: {
    computed__class() {
      return (
        "g-heading " +
        (constants.styleSize[this.styleSize] !== undefined
          ? ` ${constants.styleSize[this.styleSize]}`
          : "") +
        (this.marginBottom8 ? " g-heading-mb-8" : "") +
        (this.marginBottom0 ? " g-heading-mb-0" : "")
      );
    }
  }
});
</script>
<style scoped>
.g-heading-xl {
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 2rem;
  line-height: 1.125;
  display: block;
  margin-top: 0;
  margin-bottom: 1rem;
}
@media print {
  .g-heading-xl {
    color: #000000;
  }
}
@media print {
  .g-heading-xl {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-heading-xl {
    font-size: 3.5rem;
    line-height: 1.15;
  }
}
@media print {
  .g-heading-xl {
    font-size: 32pt;
    line-height: 1.15;
  }
}
@media (min-width: 40.0625em) {
  .g-heading-xl {
    margin-bottom: 1rem;
  }
}
.g-heading-l {
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 2rem;
  line-height: 1.2;
  display: block;
  margin-top: 3.5rem;
  margin-bottom: 0.5rem;
}
@media print {
  .g-heading-l {
    color: #000000;
  }
}
@media print {
  .g-heading-l {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-heading-l {
    font-size: 2.5rem;
    line-height: 1.25;
  }
}
@media print {
  .g-heading-l {
    font-size: 24pt;
    line-height: 1.05;
  }
}
@media (min-width: 40.0625em) {
  .g-heading-l {
    margin-bottom: 30px;
  }
}
.g-heading-m {
  color: #0b0c0c;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 1.5rem;
  line-height: 1.25;
  display: block;
  margin-top: 2.5rem;
  margin-bottom: 0.5rem;
}
@media print {
  .g-heading-m {
    color: #000000;
  }
}
@media print {
  .g-heading-m {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-heading-m {
    font-size: 1.5rem;
    line-height: 1.25;
  }
}
@media print {
  .g-heading-m {
    font-size: 18pt;
    line-height: 1.15;
  }
}
@media (min-width: 40.0625em) {
  .g-heading-m {
    margin-bottom: 0.5rem;
  }
}
.g-heading-s {
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 1.25rem;
  line-height: 1.25;
  display: block;
  margin-top: 2.5rem;
  margin-bottom: 0.5rem;
}
@media print {
  .g-heading-s {
    color: #000000;
  }
}
@media print {
  .g-heading-s {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-heading-s {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
}
@media print {
  .g-heading-s {
    font-size: 14pt;
    line-height: 1.15;
  }
}
@media (min-width: 40.0625em) {
  .g-heading-s {
    margin-bottom: 0.5rem;
  }
}
.g-body-l + .g-heading-l,
.g-body-lead + .g-heading-l {
  padding-top: 5px;
}
@media (min-width: 40.0625em) {
  .g-body-l + .g-heading-l,
  .g-body-lead + .g-heading-l {
    padding-top: 10px;
  }
}
.g-body-m + .g-heading-l,
.g-body + .g-heading-l,
.g-body-s + .g-heading-l,
.g-list + .g-heading-l {
  padding-top: 15px;
}
@media (min-width: 40.0625em) {
  .g-body-m + .g-heading-l,
  .g-body + .g-heading-l,
  .g-body-s + .g-heading-l,
  .g-list + .g-heading-l {
    padding-top: 20px;
  }
}
.g-body-m + .g-heading-m,
.g-body + .g-heading-m,
.g-body-s + .g-heading-m,
.g-list + .g-heading-m,
.g-body-m + .g-heading-s,
.g-body + .g-heading-s,
.g-body-s + .g-heading-s,
.g-list + .g-heading-s {
  padding-top: 5px;
}
@media (min-width: 40.0625em) {
  .g-body-m + .g-heading-m,
  .g-body + .g-heading-m,
  .g-body-s + .g-heading-m,
  .g-list + .g-heading-m,
  .g-body-m + .g-heading-s,
  .g-body + .g-heading-s,
  .g-body-s + .g-heading-s,
  .g-list + .g-heading-s {
    padding-top: 10px;
  }
}
.g-heading-xs {
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 1.125rem;
  line-height: 1.25;
  display: block;
  margin-top: 2.5rem;
  margin-bottom: 0.5rem;
}
@media print {
  .g-heading-xs {
    color: #000000;
  }
}
@media print {
  .g-heading-xs {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-heading-xs {
    font-size: 0.9375rem;
    line-height: 1.31579;
  }
}
@media print {
  .g-heading-xs {
    font-size: 13pt;
    line-height: 1.15;
  }
}
@media (min-width: 40.0625em) {
  .g-heading-xs {
    margin-bottom: 0.5rem;
  }
}
.g-body-m + .g-heading-xs,
.g-body + .g-heading-xs,
.g-body-s + .g-heading-xs,
.g-list + .g-heading-xs {
  padding-top: 5px;
}
@media (min-width: 40.0625em) {
  .g-body-m + .g-heading-xs,
  .g-body + .g-heading-xs,
  .g-body-s + .g-heading-xs,
  .g-list + .g-heading-xs {
    padding-top: 10px;
  }
}
.g-heading-xxs {
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 1rem;
  line-height: 1.25;
  display: block;
  margin-top: 2.5rem;
  margin-bottom: 15px;
}
@media print {
  .g-heading-xxs {
    color: #000000;
  }
}
@media print {
  .g-heading-xxs {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-heading-xxs {
    font-size: 0.875rem;
    line-height: 1.31579;
  }
}
@media print {
  .g-heading-xxs {
    font-size: 12pt;
    line-height: 1.15;
  }
}
@media (min-width: 40.0625em) {
  .g-heading-xxs {
    margin-bottom: 20px;
  }
}
.g-body-m + .g-heading-xxs,
.g-body + .g-heading-xxs,
.g-body-s + .g-heading-xxs,
.g-list + .g-heading-xxs {
  padding-top: 5px;
}
@media (min-width: 40.0625em) {
  .g-body-m + .g-heading-xxs,
  .g-body + .g-heading-xxs,
  .g-body-s + .g-heading-xxs,
  .g-list + .g-heading-xxs {
    padding-top: 10px;
  }
}
.g-heading-mb-8 {
  margin-bottom: 8px;
}
.g-heading-mb-0 {
  margin-bottom: 0px;
}
.g-hint > * {
  margin-top: 0px;
}
</style>
