// packages/govtnz-ds/build_src/vue-ts/Accordion.vue
<template>
  <div class="g-accordion" role="contentinfo">
    <slot></slot>
  </div>
</template>
<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: {
    children: { required: false, default: " Example Accordion content " }
  },
  computed: {}
});
</script>
<style scoped>
.g-accordion {
  border: 1px solid red;
}
</style>

// packages/govtnz-ds/build_src/react-js-styled-components/Accordion.js
import React from "react";
import styled from "styled-components";

const StyledDiv = styled.div`
  border: 1px solid red;
`;

const Accordion = ({ children }) => (
  <StyledDiv role="contentinfo">
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment> Example Accordion content </React.Fragment>
    )}
  </StyledDiv>
);

export default Accordion;
